"""Initial migration

Revision ID: 2fda4ccbd6a1
Revises: c0ed633cdcf7
Create Date: 2026-02-27 00:21:53.719631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fda4ccbd6a1'
down_revision: Union[str, None] = 'c0ed633cdcf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
