"""Add missing tables (Lobby, Loan, Favor, PowerCastEvent, RaceResult)

Revision ID: 3d8128c93b8d
Revises: a5f2e8c91d3b
Create Date: 2026-03-06 17:06:48.299776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d8128c93b8d'
down_revision: Union[str, None] = 'a5f2e8c91d3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lobbies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('join_code', sa.String(length=8), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('host_user_id', sa.Integer(), nullable=True),
    sa.Column('max_players', sa.Integer(), nullable=True),
    sa.Column('current_race_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['current_race_id'], ['races.id'], ),
    sa.ForeignKeyConstraint(['host_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lobbies_join_code'), 'lobbies', ['join_code'], unique=True)
    op.create_table('power_cast_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('power_id', sa.String(), nullable=True),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('effective_duration_s', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pce_race_target', 'power_cast_events', ['race_id', 'target_id'], unique=False)
    op.create_index('ix_pce_user_race', 'power_cast_events', ['user_id', 'race_id'], unique=False)
    op.create_index(op.f('ix_power_cast_events_id'), 'power_cast_events', ['id'], unique=False)
    op.create_table('race_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('horse_id', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('finish_time_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_race_results_id'), 'race_results', ['id'], unique=False)
    op.add_column('bets', sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('loans', sa.Column('amount_paid', sa.Float(), nullable=True))
    op.add_column('loans', sa.Column('amount_due', sa.Float(), nullable=True))
    op.add_column('markets', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('races', sa.Column('num_horses', sa.Integer(), nullable=True))
    op.add_column('races', sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('races', 'settled_at')
    op.drop_column('races', 'num_horses')
    op.drop_column('markets', 'closed_at')
    op.drop_column('loans', 'amount_due')
    op.drop_column('loans', 'amount_paid')
    op.drop_column('bets', 'settled_at')
    op.drop_index(op.f('ix_race_results_id'), table_name='race_results')
    op.drop_table('race_results')
    op.drop_index(op.f('ix_power_cast_events_id'), table_name='power_cast_events')
    op.drop_index('ix_pce_user_race', table_name='power_cast_events')
    op.drop_index('ix_pce_race_target', table_name='power_cast_events')
    op.drop_table('power_cast_events')
    op.drop_index(op.f('ix_lobbies_join_code'), table_name='lobbies')
    op.drop_table('lobbies')
    # ### end Alembic commands ###
